In [ ]:
# this project is all about how the predictions are going to change when you change the hyperparamets

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
df = sns.load_dataset('iris')

In [ ]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [ ]:
# we are not preprocessing and cleaning the data as it is already done
#the file is already preprocessed and cleaned in seaborn
from sklearn.model_selection import train_test_split

In [ ]:
X=df.drop('species',axis=1)
Y=df['species']

In [ ]:
X

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [ ]:
# when we do cross validation we dont need to do train test split
#and still iam not using cross validation so doing train test split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
                X, Y, test_size=0.33, random_state=42)

In [ ]:
# for creating model we have to train the training data and testing helps in prediction
# using diff algo to see how paramenters affects

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
model_knn= KNeighborsClassifier(n_neighbors=13)

In [ ]:
model_knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=13)

In [ ]:
model_knn.score(X_test,y_test)

1.0

In [ ]:
# now using diff algo
from sklearn.svm import SVC

In [ ]:
model_svm = SVC(gamma="auto")

In [ ]:
model_svm.fit(X_train,y_train)

SVC(gamma='auto')

In [ ]:
model_svm.score(X_test,y_test)

1.0

In [ ]:
# here we have changed the hyperparameters so many times for both algos and checked the different scores

In [ ]:
#now we will find the best hyperparameters using Grid Search CV
from sklearn.model_selection import GridSearchCV

In [ ]:
classifier = GridSearchCV((model_svm),{
    'C': [1,10,20,30],
    'kernel' : ['rbf','linear'],
},cv=5,return_train_score=False)

In [ ]:
classifier.fit(X,Y)# here we dont need to do train test split beacuse it is not usied in cross validation
# thats why directly using x and y

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [ ]:
classifier.cv_results_

{'mean_fit_time': array([0.02286668, 0.00994964, 0.00632443, 0.00575848, 0.00572438,
        0.00666461, 0.0103148 , 0.00718446]),
 'std_fit_time': array([0.0085437 , 0.00976754, 0.00242859, 0.00263888, 0.0014694 ,
        0.00368547, 0.00514754, 0.00473205]),
 'mean_score_time': array([0.01608434, 0.00352716, 0.00482574, 0.00517178, 0.00428686,
        0.00398755, 0.00669031, 0.00364904]),
 'std_score_time': array([0.00341267, 0.00052164, 0.00165767, 0.0034937 , 0.00184622,
        0.00219018, 0.00440171, 0.00076825]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        , 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
        0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.93333333, 0.9       ]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667, 0.96      , 0.96      ]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
        0.0421637 , 0.03887301, 0.04898979]),
 'rank_test_score': array([1, 1, 1, 4, 5, 6, 7, 7], dtype=int32)}

In [ ]:
results = pd.DataFrame(classifier.cv_results_)

In [ ]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.022867,0.008544,0.016084,0.003413,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.009950,0.009768,0.003527,0.000522,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.006324,0.002429,0.004826,0.001658,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.005758,0.002639,0.005172,0.003494,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.005724,0.001469,0.004287,0.001846,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,5
5,0.006665,0.003685,0.003988,0.002190,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.010315,0.005148,0.006690,0.004402,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,7
7,0.007184,0.004732,0.003649,0.000768,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,7

In [ ]:
results[['param_C',	'param_kernel', 'mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667
6       30          rbf         0.960000
7       30       linear         0.960000

In [ ]:
#this is our final results and got to know that these are the best hyperparemeters for C , kernel and gamma

In [ ]:
#now applying Random Searc CV
from sklearn.model_selection import RandomizedSearchCV

In [ ]:
classifier_r = RandomizedSearchCV((model_svm),{
    'C': [1,10,20,30],
    'kernel' : ['rbf','linear'],
},n_iter=4,cv=5,return_train_score=False)

In [ ]:
classifier_r.fit(X,Y)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=4,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [ ]:
classifier_r.cv_results_

{'mean_fit_time': array([0.00557356, 0.00757923, 0.00476613, 0.00715389]),
 'std_fit_time': array([0.00070307, 0.00325177, 0.00014703, 0.00244426]),
 'mean_score_time': array([0.00397615, 0.00559435, 0.00364041, 0.00351768]),
 'std_score_time': array([0.00013876, 0.00211159, 0.00014364, 0.00038679]),
 'param_kernel': masked_array(data=['rbf', 'linear', 'linear', 'linear'],
              mask=[False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_C': masked_array(data=[1, 10, 30, 20],
              mask=[False, False, False, False],
        fill_value=999999),
 'params': [{'kernel': 'rbf', 'C': 1},
  {'kernel': 'linear', 'C': 10},
  {'kernel': 'linear', 'C': 30},
  {'kernel': 'linear', 'C': 20}],
 'split0_test_score': array([0.96666667, 1.        , 1.        , 1.        ]),
 'split1_test_score': array([1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.9       , 0.93333333]),
 'split4_test_score': array([1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.97333333, 0.96      , 0.96666667]),
 'std_test_score': array([0.01632993, 0.03887301, 0.04898979, 0.0421637 ]),
 'rank_test_score': array([1, 2, 4, 3], dtype=int32)}

In [ ]:
resultss = pd.DataFrame(classifier_r.cv_results_)

In [ ]:
resultss

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.005574,0.000703,0.003976,0.000139,rbf,1,"{'kernel': 'rbf', 'C': 1}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.007579,0.003252,0.005594,0.002112,linear,10,"{'kernel': 'linear', 'C': 10}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,2
2,0.004766,0.000147,0.003640,0.000144,linear,30,"{'kernel': 'linear', 'C': 30}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,4
3,0.007154,0.002444,0.003518,0.000387,linear,20,"{'kernel': 'linear', 'C': 20}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,3

In [ ]:
resultss[['param_C',	'param_kernel', 'mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1       10       linear         0.973333
2       30       linear         0.960000
3       20       linear         0.966667

In [ ]:
#this is the implementation of Random Search CV